name: bazel
on:
  push: null
concurrency:
  group: bazel-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  format_bazel_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: tools/format-bazel-files.sh
    - name: Check formatting diff
      run: "CHANGED_FILES=\"$(git diff-index --name-only HEAD --)\"\nif [[ -z \"${CHANGED_FILES}\" ]];\
        \ then\n  echo \"Success: no formatting changes needed.\"\n  exit 0\nfi\necho \"Found formatting\
        \ changes in the following files:\"\necho \"${CHANGED_FILES}\"\necho \"\"\necho \"Please run `tools/format-bazel-files.sh`\
        \ to apply the changes.\"\nexit 1\n"
      id: _bre_format_bazel_files
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-build-direct-${{ github.sha }}
        restore-keys: '${{ runner.os }}-build-direct-

          '
    - name: Install Flex and Bison
      run: sudo apt install bison flex libfl-dev
    - name: Build p4c
      run: bazel build //... --verbose_failures
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-build-indirect-${{ github.sha }}
        restore-keys: '${{ runner.os }}-build-indirect-

          '
      if: '!cancelled() && steps._bre_format_bazel_files.conclusion == ''success'''
    - name: Install Flex and Bison
      run: sudo apt install bison flex libfl-dev
      if: '!cancelled() && steps._bre_format_bazel_files.conclusion == ''success'''
    - name: Build bazel/example
      run: cd ./bazel/example && bazel build //... --verbose_failures
      if: '!cancelled() && steps._bre_format_bazel_files.conclusion == ''success'''
